env: "dev"

server:
  port: "8080"
  timeout: 4s
  idle_timeout: 30s

postgres:
  host: ""
  port: "5432"
  user: ""
  password: ""
  dbname: ""
  sslmode: ""
  pool:
    max_open_conns: 25
    max_idle_conns: 10
    conn_max_lifetime: 30m
    conn_max_idle_time: 10m

consumer:
  type: "kafka"
  kafka:
    brokers:  
      - "kafka:9092"
    topic: "metrics"
    group_id: "persister-group"