{
 "title": "Api Service Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Requests Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(api_service_requests_total[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_service_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(api_service_requests_failed_total[5m])) by (method)/ sum(rate(api_service_requests_total[5m])) by (method) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}