{
 "title": "Cache Service Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Cache Hit Rate(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(cache_requests_total{operation=\"get\", status=\"hit\"}[5m]) / rate(cache_requests_total{operation=\"get\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(cache_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(cache_operation_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=\"cache-service\"} | json | level=\"ERROR\" [1m]))"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=\"cache-service\"} | json[5m]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"cache-service\"}"
    }
   ]
  }
 ]
}