{
 "title": "Collector Service Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "GitHub Stars: golang/go",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS \"time\",\n  value AS \"stars\"\nFROM metrics WHERE source = 'GitHub' AND name = 'stargazers_count' AND $__timeFilter(collected_at) ORDER BY collected_at ASC"
    }
   ]
  },
  {
   "title": "Temperature in London",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS \"time\",\n  value AS \"temp\"\nFROM metrics WHERE source='OpenWeatherMap' AND name='temperature_celsius' AND $__timeFilter(collected_at) ORDER BY collected_at ASC "
    }
   ]
  },
  {
   "title": "Uptime: google.com",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n  collected_at AS \"time\",\n  value AS \"uptime\"\nFROM metrics WHERE source = 'UptimeChecker' AND name = 'availability_percent' AND $__timeFilter(collected_at) ORDER BY collected_at ASC "
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method, path) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gorutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"collector-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocation (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"collector-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\", job=\"collector-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}