{
 "title": "Notification Service Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Notification Send Duration (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(notification_service_notification_send_duration_seconds_bucket[5m])) by (le, notifier_type))",
     "legendFormat": "{{notifier_type}}"
    }
   ]
  },
  {
   "title": "Notification Pipeline Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(notification_service_notifications_consumed_total[5m]))",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(rate(notification_service_notifications_sent_total[5m])) by (notifier_type)",
     "legendFormat": "Sent - {{notifier_type}}"
    }
   ]
  },
  {
   "title": "Errors by Stage and Notifier Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(notificaiton_service_notification_errors_total[5m])) by (stage, notifier_type)",
     "legendFormat": "{{stage}} - {{notifier_type}}"
    }
   ]
  },
  {
   "title": "Notification Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(notificaiton_service_notification_errors_total[5m])) / sum(rate(notification_service_notifications_consumed_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=\"notification-service\"} | json | level=\"ERROR\" [1m]))"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=\"notification-service\"} | json[5m]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"notification-service\"}"
    }
   ]
  }
 ]
}