{
 "title": "Persister Service Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Metrics Pipeline Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(persister_service_metrics_consumed_total[5m]))",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(rate(persister_service_metrics_saved_total[5m]))",
     "legendFormat": "Saved"
    }
   ]
  },
  {
   "title": "Database Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "sum(rate(persister_service_database_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Save Success Ratio (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(persister_service_metrics_saved_total[5m])) / sum(rate(persister_service_metrics_consumed_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=\"persister-service\"} | json | level=\"ERROR\" [1m]))"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=\"persister-service\"} | json[5m]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"persister-service\"}"
    }
   ]
  }
 ]
}