{
 "title": "System Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Hotspots",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (count_over_time({container=~\".+\"} | json | level=\"ERROR\"[1h]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Metrics Ingestion Rate",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "metrics/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Data Pipeline Throughput",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(persister_service_metrics_consumed_total[5m]))",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(rate(persister_service_metrics_saved_total[5m]))",
     "legendFormat": "Saved to DB"
    },
    {
     "expr": "sum(rate(notification_service_notifications_sent_total[5m]))",
     "legendFormat": "Notifications Sent"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(cache_requests_total{operation=\"get\", status=\"hit\"}[5m])) / sum(rate(cache_requests_total{operation=\"get\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(api_service_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Error Feed",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=~\".+\"} | json | level=\"ERROR\""
    }
   ]
  },
  {
   "title": "Top 5 API Methods by Trafic",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (method) (rate(api_service_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}