env: "dev"

server:
  port: "8080"
  timeout: 4s
  idle_timeout: 30s

urls:
  cache_service: "cache-service:50051"

worker:
  poll_interval: 1m

github:
  token: ""
  repository: "golang/go"

open_weather:
  api_key: ""
  city: ""

broker:
  type: "kafka"
  kafka:
    brokers:  
      - "kafka:9092"
    topic: "metrics"