env: "dev"

server:
  port: "8080"
  timeout: 4s
  idle_timeout: 30s

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

worker:
  poll_interval: 1m

github:
  token: ""
  repository: "golang/go"

open_weather:
  api_key: ""
  city: ""

broker:
  type: "kafka"
  kafka:
    brokers:  
      - "kafka:9092"
    topic: "metrics"