env: "dev"

server:
  port: "3000"
  timeout: 4s
  idle_timeout: 30s

postgres:
  host: "localhost"
  port: "5432"
  user: "user"
  password: "password"
  dbname: "metrics_db"
  sslmode: "disable"
  pool:
    max_open_conns: 25
    max_idle_conns: 10
    conn_max_lifetime: 30m
    conn_max_idle_time: 10m

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

worker:
  poll_interval: 1m

github:
  token: "here_will_be_token"
  repository: "golang/go"

open_weather:
  api_key: "here_will_be_api_key"
  city: "London"